### ISSUE TITLE
Make Flatpak package

### ISSUE THREAD

**Issue by TheEvilSkeleton** [terrarier2111/Leafish#104]
[Flatpak](https://flatpak.org) is a universal package manager for Linux. [Flathub](https://flathub.org) is one of Flatpak's repo (remote) which includes a build system. Alternatively we can use GitHub CI to create Flatpak bundles: https://github.com/marketplace/actions/flatpak-builder.

I'm quite familiar with Flatpak so I can create a manifest.

---

I don't have a Minecraft account, so I'd like others to test it for me. If you want to test, please read the instructions at https://github.com/terrarier2111/Leafish/issues/104#issuecomment-913779965.

**Comment by rowbawts** [comment]
I was actually getting ready to suggest this I use Silverblue which "for the most part" requires (prefers) Flatpaks.

**Comment by PureTryOut** [comment]
> I'm quite familiar with Flatpak so I can create a manifest.

Feel free to pick up this issue! I´ve assigned you for now.

**Comment by TheEvilSkeleton** [comment]
So I just opened MR #111.

I got it working:

![image](https://user-images.githubusercontent.com/50847364/132245540-4f370424-de6d-4afb-b03b-ecab8c21d71e.png)

Sadly I do not have a Minecraft account, so if anyone is willing to test it for me, please give some feedback.

**Comment by rowbawts** [comment]
I'll test I have a Minecraft account do you have this hosted on the Flathub testing repo?

**Comment by TheEvilSkeleton** [comment]
I don't want to use Flathub now since I'm waiting for a Leafish release. You can head over to https://github.com/TheEvilSkeleton/Leafish/pull/1, click on `Details` next to `Packaging / Flatpak (x86_64) (pull request)` (aarch64 for ARM64). You'll see a "Download artifact" button and download the zip file. Finally, extract the zip file, go inside the extracted directory if any and run `flatpak install leafish.flatpak`.

**Comment by rowbawts** [comment]
> I don't want to use Flathub now since I'm waiting for a Leafish release. You can head over to [TheEvilSkeleton#1](https://github.com/TheEvilSkeleton/Leafish/pull/1), click on `Details` next to `Packaging / Flatpak (x86_64) (pull request)` (aarch64 for ARM64) at the bottom of the MR. You'll see a "Download artifact" button, so click that and download the zip file. Finally, extract the zip file, go inside the extracted directory if any and run `flatpak install leafish.flatpak`. You should see a desktop entry after it's installed, and you'll be able to launch it from there.

Ok I've got installed and I'm logged in I will join a server now and report back.

**Comment by rowbawts** [comment]
Ok so I was able to connect to Hypixel but the cursor doesn't get locked to the window not sure if that's upstream or specific but bottom line is it works. I'm assuming all other oddities are just non implemented features.

![Screenshot from 2021-09-06 13-26-31](https://user-images.githubusercontent.com/13012832/132249020-9c31dd7b-c877-4595-8b3e-bac10bb42e27.png)

**Comment by penloy** [comment]
> Ok so I was able to connect to Hypixel but the cursor doesn't get locked to the window not sure if that's upstream or specific to the Flatpak but bottom line is it works. I'm assuming all other oddities are just non implemented features.
> 
> ![Screenshot from 2021-09-06 13-26-31](https://user-images.githubusercontent.com/13012832/132249020-9c31dd7b-c877-4595-8b3e-bac10bb42e27.png)

It works for me with cursor locked in the window.

![image](https://user-images.githubusercontent.com/68067125/132249225-85a41de6-e2ee-4b24-a446-fd7011067153.png)

**Comment by TheEvilSkeleton** [comment]
> Ok so I was able to connect to Hypixel but the cursor doesn't get locked to the window not sure if that's upstream or specific to the Flatpak but bottom line is it works. I'm assuming all other oddities are just non implemented features.
> 
> ![Screenshot from 2021-09-06 13-26-31](https://user-images.githubusercontent.com/13012832/132249020-9c31dd7b-c877-4595-8b3e-bac10bb42e27.png)

Hmm... can you try to download https://github.com/terrarier2111/Leafish/suites/3693742881/artifacts/90071216 and see if you are having this issue in a native binary or not?

**Comment by rowbawts** [comment]
> > Ok so I was able to connect to Hypixel but the cursor doesn't get locked to the window not sure if that's upstream or specific to the Flatpak but bottom line is it works. I'm assuming all other oddities are just non implemented features.
> > ![Screenshot from 2021-09-06 13-26-31](https://user-images.githubusercontent.com/13012832/132249020-9c31dd7b-c877-4595-8b3e-bac10bb42e27.png)
> 
> Hmm... can you try to download https://github.com/terrarier2111/Leafish/suites/3693742881/artifacts/90071216 and see if you are having this issue in a native binary or not?

Same thing in native so that rules that out.

![Screenshot from 2021-09-06 13-36-51](https://user-images.githubusercontent.com/13012832/132249560-77fbacb8-be98-4691-8d80-8c6dedfac01f.png)

**Comment by TheEvilSkeleton** [comment]
In that case I'd suggest opening a new issue.

**Comment by rowbawts** [comment]
Well I found this I probably should've looked first https://github.com/terrarier2111/Leafish/issues/36
