### ISSUE TITLE
Binaries for lazy people / other distros

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [terrarier2111/Leafish#48]
There are artifacts in stevenarella, it would be a nice to have here as well

**Comment by terrarier2111** [comment]
This would be cool, I agree we will do some more planning(and improve the structure of this project) after the deadline for iceiix to respond is reached or he answers and we know how we'll proceed.

**Comment by PureTryOut** [comment]
Oh if Stevenarella has that, then we can probably quite easy replicate that here. I'll look into it soon.

**Comment by PureTryOut** [comment]
I've modified the CI to generate these now. Every commit in `main` and every PR has binaries generated, available from Github actions.
