### ISSUE TITLE
Persistent smaller menu (MiniHUD)

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [terrarier2111/Leafish#55]
adding persistent smaller menu like MiniHUD mod does. This way you see things like FPS and coordinates all the time, but when pressing F3 you see normal F3 menu instead, so this is not in contradict with #54

**Comment by terrarier2111** [comment]
But if we were to add these features I'd like to put them in some sort of addon with our (future) client api or at least make these features toggleable for streamers etc.

**Comment by Z2Up1UwcaYOyZq** [comment]
Yes, that's the plan

**Comment by Z2Up1UwcaYOyZq** [comment]
because I see some long term plans also on your side, maybe consider making a "long term" project board wher we could add and discuss major features, (obviously we need a playable client first)

**Comment by Z2Up1UwcaYOyZq** [comment]
since we need an API and addon support I'm closing this for now
