### ISSUE TITLE
macOS: viewport rendered at a quarter of the window size - HiDPI issue?

### ISSUE THREAD

**Issue by iceiix** [terrarier2111/Leafish#68]
<img width="1059" alt="Screen Shot 2021-09-01 at 6 01 41 PM" src="https://user-images.githubusercontent.com/43691553/131766079-80854f6d-40e0-44d0-ad68-c822441568ad.png">

macOS 11.4
iMac (Retina 5K, 27-inch, 2020)
de2d569462e91d561b77ae3c3f8a21b95cdd2d86

The graphics only render in the left-hand quadrant of the window. If I resize the window, it consistently stays within this corner, not filling the full window size. I also cannot interact with the UI, the scaling issue also appears to affect the mouse events, for example when you hover over a button it does not highlight, and nothing can be clicked successfully (was unable to add a server).

Could be an incompatibility due to the "Retina 5K" display of the iMac, which is HiDPI - in my case, has a 2x scale factor. I had a lot of trouble getting these displays working on Stevenarella, using APIs in glutin/winit to account for the difference in logical size vs physical size - regressed in Leafish?

https://github.com/iceiix/stevenarella/issues/22
https://github.com/iceiix/stevenarella/issues/419
https://github.com/iceiix/stevenarella/pull/334
https://github.com/iceiix/stevenarella/pull/268

**Comment by terrarier2111** [comment]
This should be fixed by my newest commit

**Comment by iceiix** [comment]
Thanks, appears fixed by https://github.com/terrarier2111/Leafish/commit/ad9ea74135439342563b364df0da438cbc9e9ed0 - tested on 30b43d58a8a80c023e902c0bc025444c616d2743, confirmed the viewport now takes up the full window, and can be successfully interacted with:

<img width="2672" alt="Screen Shot 2021-09-05 at 3 54 46 PM" src="https://user-images.githubusercontent.com/43691553/132143580-2e40bbf3-529d-464d-8a85-f40baa4ef225.png">
