### ISSUE TITLE
Server without Crashing

### ISSUE THREAD

**Issue by iMonZ** [terrarier2111/Leafish#73]
Hey,

is there a Testing-Server that works without crashing?
I tried a few servers, but only one chunk is loading and textures are broken.

**Comment by Z2Up1UwcaYOyZq** [comment]
having a public test server sounds like a great idea

**Comment by terrarier2111** [comment]
> Hey,
> 
> is there a Testing-Server that works without crashing?
> I tried a few servers, but only one chunk is loading and textures are broken.

What version were you using to join that server?

**Comment by PureTryOut** [comment]
I'm using [Cuberite](https://github.com/cuberite/cuberite) to test which works well. But please report the server you tried as the crashing should really be fixed.

**Comment by iMonZ** [comment]
> > Hey,
> > is there a Testing-Server that works without crashing?
> > I tried a few servers, but only one chunk is loading and textures are broken.
> 
> What version were you using to join that server?

How can I see or change the version? I couldn't find any setting for that. (I joined servers that are running 1.16)

**Comment by iMonZ** [comment]
> I'm using [Cuberite](https://github.com/cuberite/cuberite) to test which works well. But please report the server you tried as the crashing should really be fixed.

Sorry I don't mean Server (server. tool) I mean a remote server.

**Comment by terrarier2111** [comment]
> > > Hey,
> > > is there a Testing-Server that works without crashing?
> > > I tried a few servers, but only one chunk is loading and textures are broken.
> > 
> > 
> > What version were you using to join that server?
> 
> How can I see or change the version? I couldn't find any setting for that. (I joined servers that are running 1.16)

Can you give me some more information about your setup? (os, graphics card, montors) also are there any errors in the log?

**Comment by iMonZ** [comment]
> > > > Hey,
> > > > is there a Testing-Server that works without crashing?
> > > > I tried a few servers, but only one chunk is loading and textures are broken.
> > > 
> > > 
> > > What version were you using to join that server?
> > 
> > 
> > How can I see or change the version? I couldn't find any setting for that. (I joined servers that are running 1.16)
> 
> Can you give me some more information about your setup? (os, graphics card, montors) also are there any errors in the log?

Don’t understand me wrong this is not an crash report the server that I tried had a high version number or are pretty complex (like hypixel etc etc)
Less complex server (like survival only) are working pretty fine.
With this issue I just wanted to ask if there is a special testing server that you are using to test the features of the client.

oh btw: OS: macOS 12 (21A5506j) GPU: RX 580 nitro + Monitors?: BENQ 1920x1080, LG 1920x1080

I do not have the logs because I haven’t run the game in cli mode but I can try that out

**Comment by iMonZ** [comment]
All right so I think everything under 1.13 should be fine
