### ISSUE TITLE
macOS packaging

### ISSUE THREAD

**Issue by iMonZ** [terrarier2111/Leafish#74]
Hey,

could you put the Leafish.app into a Leafish.app folder before zipping it?

Currently, you have: Leafish.app.zip/Contens where you need to unzip it and create a new folder called Leafish.app and pasting the Contents folder into it.

This would make everything easier! Thanks

**Comment by PureTryOut** [comment]
I was messing with it and the only thing I managed to do was create a `Leafish.app.zip.zip` which is annoying... But I suppose that is better than what is there now, I'll change it.

**Comment by iMonZ** [comment]
> I was messing with it and the only thing I managed to do was create a `Leafish.app.zip.zip` which is annoying... But I suppose that is better than what is there now, I'll change it.

Thanks it's better than nothing but have you pushed the change already?
