### ISSUE TITLE
Random tick implementation

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [terrarier2111/Leafish#80]
This is what makes plants grow

**Comment by PureTryOut** [comment]
That seems to be a single player thing no?

**Comment by iMonZ** [comment]
> That seems to be a single player thing no?

The ticks are managed by the server. So yeah. (You could add a single player mode with just an MC server in the background xD)

**Comment by terrarier2111** [comment]
This hasn't got anthing to do with the client, so i'm gonna close this for now.
