### ISSUE TITLE
Support Android client

### ISSUE THREAD

**Issue by codingwatching** [terrarier2111/Leafish#98]
Hi @terrarier2111 It is best if we Leafish can support Android client
Is this possible now or near in the future?
Thank you

**Comment by terrarier2111** [comment]
I think this would be a great feature but i'd like to make the client playable first and support the main features of all major versions starting from 1.7.10

**Comment by codingwatching** [comment]
Hi @terrarier2111 
Thank you! I hope we will use the library and framework that we can port to Android in the future after the client is playable!
